workflows:
  build_apk:
    name: Build Ionic APK
    environment:
      node: 20.19.0
      java: 21
      vars:
        PACKAGE_NAME: "io.ionic.movieses"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
